# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='traveled_with',
            new_name='travelers',
        ),
    ]
