# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0002_auto_20170725_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='travelers', to='python_belt.User'),
        ),
    ]
